import { type Metadata } from "next";
import { Quicksand } from "next/font/google";
import "../globals.css";
import "../custom.css";
import Providers from "@/context/Providers";
import { Toaster } from "@/components/ui/sonner";
import Header from "@/components/shared/Header";

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`dark font-quicksand ${quicksand.variable} antialiased`}>
        <Providers>
          <>
            <Toaster theme="dark" duration={3000} />
            <Header />
            <main className="pt-16">{children}</main>
          </>
        </Providers>
      </body>
    </html>
  );
}
