import { type Metadata } from "next";
import Link from "next/link";
import { SignedIn, UserButton } from "@clerk/nextjs";
import { Quicksand } from "next/font/google";
import "../globals.css";
import "../custom.css";
import Providers from "@/context/Providers";
import ConnectBank from "@/components/dashboard/ConnectBank";
import { Toaster } from "@/components/ui/sonner";

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`dark font-quicksand ${quicksand.variable} antialiased`}>
        <Providers>
          <>
            <Toaster theme="dark" duration={3000} />
            <header className="bg-neutral-900 z-50 flex justify-between items-center fixed top-0 inset-x-0 p-4 gap-4 h-16">
              <Link className="space-x-4 flex items-center" href="/">
                <span className="font-bold text-orange-500 text-5xl">₹</span>
                <span className="font-semibold text-2xl">Fiscus</span>
              </Link>
              <div className="space-x-4">
                <SignedIn>
                  <div className="flex justify-center items-center gap-2">
                    <ConnectBank />
                    <UserButton />
                  </div>
                </SignedIn>
              </div>
            </header>
            <main className="pt-16">{children}</main>
          </>
        </Providers>
      </body>
    </html>
  );
}
